import { getSession, signOut } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Title from '../components/title'


export default function Home({session}) {

  return (
    <>
      <Head>
        <title>Patojito Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.description}>
          <Title>SPORT STORE PATOJITO</Title>
          <Navbar />
          <button onClick={() => signOut()}>
            LOGOUT
          </button>
          <div className='image'>
              <img
                src={session.user.image}
                alt="avatar"
                className={styles.vercelLogo}
                width={45}
                height={45}
                priority="false"
              />
          </div>
        </div>
        <div className={styles.center}>
          <h1>Tienda Deportiva</h1>
          <Image
            className={styles.logo}
            src="/2.jpg"
            alt="foto 2"
            width={380}
            height={450}
            priority="false"
          />
        </div>

        <div className={styles.grid}>
          
        </div>
      </main>
        <style jsx>
          {`
            button {
              padding: 1rem;
              border-radius: 12px;
              margin-left: 15%;
            }  
            .image {
              margin-left: -5%
            }         
          `}
        </style>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context)

  if (!session) return {
    redirect: {
      destination: '/login',
      permanent: false}
  }

  return {
    props: {
      session
    }
  }
}
