// import { useSession } from "next-auth/react"
import { useRouter } from 'next/router'
import { getSession, signOut } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home({session}) {

  return (
    <>
      <Head>
        <title>Patojito Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>
            SPORT STORE PATOJITO
          </h1>
         <Navbar />
          <div>
              <img
                src={session.user.image}
                alt="avatar"
                className={styles.vercelLogo}
                width={45}
                height={45}
                priority
              />
          </div>
          <button onClick={() => signOut()}>
            LOGOUT
          </button>
        </div>
        <div className={styles.center}>
          <h1>Tienda Deportiva</h1>
          <Image
            className={styles.logo}
            src="/2.jpg"
            alt="foto 2"
            width={380}
            height={450}
          />
        </div>

        <div className={styles.grid}>
          
        </div>
      </main>
        <style jsx>
          {`
            button {
              padding:1.2%
            }           
          `}
        </style>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context)

  if (!session) return {
    redirect: {
      destination: '/login',
      permanent: false}
  }

  return {
    props: {
      session
    }
  }
}
